repos:
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      # - id: clippy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: pretty-format-json
        args: ["--autofix"]
      - id: fix-byte-order-marker
      - id: check-ast
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-vcs-permalinks
      - id: trailing-whitespace
      - id: mixed-line-ending
